"""empty message

Revision ID: fba896fea3c6
Revises: 7eac718c5351
Create Date: 2021-03-08 16:06:43.673210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba896fea3c6'
down_revision = '7eac718c5351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_game_created_at'), 'game', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_created_at'), table_name='game')
    # ### end Alembic commands ###
